### ISSUE TITLE
Develop icon set

### ISSUE THREAD

**Issue by timklapdor** [UAMediaProd/uoa-styles#5]
Decide to use an existing icon set for use. Should have options around deployment - font & svg as minimum. 

- Font Awesome - pay for updated pro licence?
- https://iconsvg.xyz/

**Comment by timklapdor** [comment]
Alternative https://github.com/Remix-Design/remixicon

**Comment by alexfimerix** [comment]
Request from Marketing to use Font Awesome as our icon set: 

With respect to colour green for the tick/success icon, we don’t have a green in the current or updated palette so that would be at your discretion. What we would ask is that you use font awesome for any icons you are using in your content. The current VI uses font awesome V4.7 and this will be updated to the latest version in the update (either version 5 or 6 depending on when they release 6 from beta). There is some information on the icons in the current Style Guide here: https://styleguide-v2.adelaide.edu.au/icon-font.html
